// <auto-generated />
namespace DA2_SistemaEscolar2016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class camposRequeridosAlumno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(camposRequeridosAlumno));
        
        string IMigrationMetadata.Id
        {
            get { return "201609201540216_camposRequeridosAlumno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
