// <auto-generated />
namespace DA2_SistemaEscolar2016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class entidad_archivo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entidad_archivo));
        
        string IMigrationMetadata.Id
        {
            get { return "201611280733509_entidad_archivo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
